FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm install

RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && node src/index.js"]

