docker run -d \                                                                                                                                     ─╯
  --name postgres-db \
  --network k8s-network \
  -e POSTGRES_USER=admin \
  -e POSTGRES_PASSWORD=secret \
  -e POSTGRES_DB=postgres \
  -p 5432:5432 \
  -v postgres_data:/var/lib/postgresql/data \
  postgres:15




# URL
# DATABASE_URL="postgres://admin:secret@localhost:5432/postgres"